### ISSUE TITLE
"Reboot NGINX"-function is rebooting wrong service

### ISSUE THREAD

**Issue by SuddenlyRust** [itorgov/laravel-forge-bot#5]
When I try to use "Reboot NGINX" it won't reboot my nginx service but instead it rebooted my php7.4-fpm service. I did provision the server on AWS. 

Other functions are working correct. Well done Igor 💪

**Comment by itorgov** [comment]
Hmm.. I'll check it.

P.S.: Actually I'm Ivan, not Igor :-) Btw, thanks!

**Comment by itorgov** [comment]
I checked it and all seems to be working.
What do you see in "Recent Events" section on your Forge's dashboard when you hit "Reboot NGINX" button in Telegram?

For example, I pressed "Reboot NGINX" button and then "Reboot PHP" button. As you can see, in my dashboard all is fine.
<img width="1034" alt="Screenshot 2020-04-26 at 18 01 42" src="https://user-images.githubusercontent.com/1703419/80311469-7565f500-87e8-11ea-9691-795e608030a0.png">

**Comment by SuddenlyRust** [comment]
I see the same on the Recent Events Tab
![Recent Events](https://user-images.githubusercontent.com/14092921/80311943-d2f74300-87e2-11ea-9c93-08a77521ebab.png)

But when I ssh in my machine and check the status. I see that only my php service got restarted. As you can see in the image the **nginx** service is running over 2 hours and the **php-fpm** service only got rebooted.
![Service Status](https://user-images.githubusercontent.com/14092921/80311982-12259400-87e3-11ea-9cbf-3c9cf3fd01ad.png)

And sorry with your name 😜

**Comment by itorgov** [comment]
Very interesting 🤔
Ok, I'll investigate it and I'll try to find the solution.
Maybe there is a problem in Forge's API.

**Comment by SuddenlyRust** [comment]
There's no hurry, Ivan. Thank you for the fast response 👍

I deployed that server to Digital Ocean (if this helps)

**Comment by SuddenlyRust** [comment]
Okay looks like it is a bug with the Forge API. I tried the Endpoint for [Reboot Nginx](https://forge.laravel.com/api-documentation#reboot-nginx) and it is rebooting my PHP-FPM service 😁

Gonna write a ticket. I keep you informed about the outcome 💪

**Comment by ruslansteiger** [comment]
Okay James did reply to me

> I've dug into the issue a little bit, but I'm unable to confirm that Nginx is not being restarted. What you may have run into is that when we reload (I'm finding out why we don't call restart) Nginx, we may also restart the PHP-FPM processes if they need to be restarted.

Looks like they are calling `nginx reload` and this does not reset the running time counter of the service. So it was my mistake to only look at the run time of the service. But if you check your worker IDs you will see that new worker processes are spawned.

My mistake. No issue here 😁
